#服务器配置
server:
   port: 8088
   servlet:
       context-path: /demo
   session-timeout: 1800
   tomcat:
     accesslog:
        enabled: true
#日志信息配置
logging:
   level:
     root: info
   config: classpath:logback-boot.xml
#yml文件依赖环境
spring:
   profiles:
     active: dev
#mybatis
mybatis:
   mapperlocations: mybatis/*Mapper.xml
   typeAliasesPackage: com.springboot.Demo.**.domain
      