server:
   port: 8761
eureka:
   client:
      hostname: 127.0.0.1
      registerWithEureka: false
      fetchRegistry: false
      serverUrl:
         defaultZone:http://${eureka.instance.hostname}:${server.port}/eureka/

       
      